---
title: "Raster Data"
author: "Rick Davila"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load necessary packages

For loading the raster data *raster* package

```{r}
library(raster)
```

### Load a single band raster

```{r}
# load a single band
img <- raster('./data/LC09_L2SP_196025_20221206_20221208_02_T2_SR_B1.tif')

# display the attributes of the loaded raster
img
```

### Plot a single band

```{r}
# plot a single band
plot(img)

# histogram of the raster image
# hist(img, main='Distribution of pixel values', col='purple', maxpixels=ncell(img))

```

### Loading multiple bands

```{r}

# create the list of source files containg landsat 7 bands
landsat <- paste0('./data/LC09_L2SP_196025_20221206_20221208_02_T2_SR_B',
                  1:7,
                  '.tif')

# display the list created above
landsat

# create raster stack
landsat_stack <- stack(landsat)

# display the attributes of the created raster stack
landsat_stack

# create raster brick from the stacked layer
landsat_brick <- brick(landsat_stack)

# display the attributes of the raster brick
landsat_brick

```

### Attributes of the loaded raster layer

```{r}
# display number of cells
ncell(landsat_brick)

# display number of bands in the image
nlayers(landsat_brick)

```

### Name the bands    

```{r}
# check the original names of bands
names(landsat_brick)

# set the band names
names(landsat_brick) <- c('Coastal aerosol',
                          'Blue',
                          'Green',
                          'Red',
                          'NIR',
                          'SWIR-1',
                          'SWIR-2')

# display new names
names(landsat_brick)
```

### True Color Composite

```{r}
# plot color composite
plotRGB(landsat_brick, r = 4, g = 3, b = 2,
        axes = T, stretch = 'lin',
        main = 'Landsat True Color Composite')

# plot false color composite
plotRGB(landsat_brick, r = 5, g = 4, b = 3,
        axes = T, stretch = 'lin',
        main = 'Landsat False Color Composite')

```